# Generated by Django 5.1.5 on 2025-03-19 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='Owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='owner_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
