# Generated by Django 5.1.5 on 2025-03-19 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='listings',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
