# Generated by Django 5.1.5 on 2025-03-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_highest_bid_listing_is_closed_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg', max_length=500),
            preserve_default=False,
        ),
    ]
